### ISSUE TITLE
Game fields displayed on Overview panel

### ISSUE THREAD

**Issue by adrian5683** [fuenechaos/fluent-ui-playnite#3]
Hi, it seems that all game fields are displayed on the Overview panel regardless of whether those game fields are deselected under Settings>Appearance>Details View. The only difference is that icons appear for the fields that are enabled and missing for fields that are disabled. For example, I have both Community Score and Critic Score deselected in Settings, there are no icons or score numbers but the score bar is visible.
Is it possible to make the game fields and their icons/graphics not display when disabled in settings? Great job on theme by the way.

**Comment by fuenechaos** [comment]
Will be fixed by the next update
