### ISSUE TITLE
Position of game icon on details panel

### ISSUE THREAD

**Issue by adrian5683** [fuenechaos/fluent-ui-playnite#4]
Is it possible to replace the cover art used on the description panel with the icon that usually sits at the top of the details panel? Using the latest version of your theme I'll put the game logo where the icon currently sits via Extra Metadata extension, but I'd like to move the icon to where the cover art sits. If simple enough to fiddle around in an xaml file I'll try and do it myself.

![Capture](https://user-images.githubusercontent.com/47461694/126207088-81eb833f-7a5a-4889-b40b-b3f4bdce0167.PNG)

**Comment by fuenechaos** [comment]
Do you want to completely replace it or add it along with the cover art
i could sent you a xaml for replacing

**Comment by adrian5683** [comment]
Just replacing it would be great, much appreciated.

**Comment by adrian5683** [comment]
I figured it out for myself, this is the result.
![Capture](https://user-images.githubusercontent.com/47461694/126573494-62f555b1-9e0a-4625-b68e-7a3b6519feaf.PNG)

**Comment by fuenechaos** [comment]
oh great sorry for delaying it
